= TERN Ontology Specification
:toc: left
:toclevels: 4
:table-stripes: even
:sectnums:
:sectnumlevels: 5
:sectlinks:
:icons: font
:favicon: https://www.tern.org.au/wp-content/uploads/2019/10/favicon.png
:idprefix:

NOTE: *Status: Draft* - while the document is in draft, sections of the document may contain placheholders such as `TBA` and `TBD`. 

== Metadata

[frame=none, grid=none, cols="1s,5"]
|===
|IRI | `https://w3id.org/tern/profiles/tern/specification`
|Title | TERN Ontology Specification
|Definition | This document lists the normative requirements for data aiming to conform to the TERN Ontology. It is to be used as the authoritative, human-readable list of individual requirements from which profile artefacts such as validators are derived from.
|Created | 2022-04-06
|Modified | 2022-04-06
|Creator | link:https://linked.data.gov.au/org/tern[TERN]
|Publisher | link:https://linked.data.gov.au/org/tern[TERN]
|License | link:https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International (CC BY 4.0)]
|*Alternate document formats* | link:https://ternaustralia.github.io/ontology_tern/spec.pdf[PDF]
|===

== Preamble

=== Abstract

The TERN Ontology Specification addresses the data exchange and data representation problems with ecological field survey data to facilitate data interoperability and data integration. The specification uses the PROF vocabulary to express itself as a profile of multiple well-established Semantic Web standards and establishes links to resources and controlled vocabularies necessary to use the specification effectively.

TERN Ecosystem Surveillance have developed 19 modules to standardise ecological monitoring protocols for data collection. The working title for the monitoring protocols is _TERN Ecosystem Surveillance Ecological Monitoring Protocols_.

TERN Data Services and Analytics is developing a standardised data exchange specification to support the exchange of data collected using TERN Ecosystem Surveillance Ecological Monitoring Protocols. The working title for the data exchange specification is _Ecological Data Exchange Specification_.

The Ecological Data Exchange Specification is a profile of the ecological data model known as the link:https://linkeddata.tern.org.au/information-models/tern-ontology[TERN Ontology]. Data that is conformant to the Ecological Data Exchange Specification is also conformant to the TERN Ontology.

=== Normative Status

This specification is normative for the TERN Ontology Specification.