= TERN Ontology Specification
:toc: left
:toclevels: 4
:table-stripes: even
:sectnums:
:sectnumlevels: 5
:sectlinks:
:icons: font
:favicon: https://www.tern.org.au/wp-content/uploads/2019/10/favicon.png
:idprefix:

NOTE: *Status: Draft* - while the document is in draft, sections of the document may contain placheholders such as `TBA` and `TBD`.

== Metadata

[frame=none, grid=none, cols="1s,5"]
|===
|IRI | `https://w3id.org/tern/profiles/tern/specification`
|Title | TERN Ontology Specification
|Definition | This document lists the normative requirements for data aiming to conform to the TERN Ontology. It is to be used as the authoritative, human-readable list of individual requirements from which profile artefacts such as validators are derived from.
|Created | 2022-04-06
|Modified | {docdate}
|Creator | link:https://linked.data.gov.au/org/tern[TERN]
|Publisher | link:https://linked.data.gov.au/org/tern[TERN]
|License | link:https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International (CC BY 4.0)]
|*Alternate document formats* | link:https://ternaustralia.github.io/ontology_tern/spec.pdf[PDF]
|===

== Preamble

=== Abstract

The TERN Ontology Specification addresses the data exchange and data representation problems with ecological field survey data to facilitate data interoperability and data integration. The specification uses the PROF vocabulary to express itself as a profile of multiple internationally-recognised Semantic Web standards and establishes links to informative resources and controlled vocabularies necessary to use the specification.

For many years, the scientific ecological community and industry partners collected rich and insightful data about the land and ecosystems using field survey protocols. The state of the collected data was often unusable for prompt nationwide reporting and data analysis due to incompatible data storage solutions between non-standardised relational databases, spreadsheets and PDF documents. Without spending further time and money to extract, transform and integrate the data, much of the data's richness and usefulness is lost.

The solution to this problem of an ever-growing set of heterogeneous data is to use existing standards defined by the W3C and follow a so-called Linked Data set of principles. By building a specification based on existing international standards, the richness of the ecological field survey data can now serve as insights for researchers and government policy-makers. 

The TERN Ontology Specification is a profile of W3C's SOSA, SSN and PROV ontologies. It uses these ontologies to describe observations and samplings as kinds of activities on a field survey trip and associates these activities with persons and organisations. The TERN Ontology Specification also uses community-based standards such as OGC's GeoSPARQL to associate spatial features or geometries to things within a field survey trip and QUDT's Units vocabulary for associating units of measure to results of observations. The TERN Ontology Specification also provides a vast set of TERN-created ecology-based and ecology-related controlled vocabularies to describe observable properties, feature types, instruments and protocol methods. Lastly, the TERN Ontology introduces Site and Site Visit to represent survey trips to ad-hoc or permanent plots and Attribute to represent auxiliary information.

=== Normative Status

This specification is normative for the TERN Ontology Specification.

=== Standard Parts

This specification document is one of many resources that make up the TERN Ontology Standard and expresses its structure using the Profiles Vocabulary <<PROF>>.

Other parts of this standard include:

* `TBA`.

=== Namespaces

`TBD`.

== Introduction

This specification document defines the classes and properties of the TERN Ontology and the set of requirements that data validators will use to ensure conformance. This specification document also details how data providers should use related ontologies and controlled vocabularies to represent their ecological field survey data. Annex A lists these parts in more detail.

== References

[none]
* [[PROF]] <<PROF>> +
[none]
** https://www.w3.org/TR/dx-prof/[_The Profiles Vocabulary_], Nicholas J Car; Rob Atkinson. 18 December 2019. W3C Working Group Note. URL: <https://www.w3.org/TR/dx-prof/>

[none]
* [[vocab-ssn]] <<vocab-ssn>> +
[none]
** https://www.w3.org/TR/vocab-ssn/[_Semantic Sensor Network Ontology_]. Armin Haller; Krzysztof Janowicz; Simon Cox; Danh Le Phuoc; Kerry Taylor; Maxime Lefrançois. 19 October 2017. W3C Recommendation. URL: <https://www.w3.org/TR/vocab-ssn/>

:sectnums!:

== Annex A: Specification Parts

[NOTE]
This Annex is normative.

`TBD`.